image: spa_build_env
repository: https://github.com/levidousseaux/react-sample.git
stages:
  - name: Build & Test
    steps:
      - name: install
        commands:
          - echo 'node version:' $(node -v)
          - echo 'npm version:' $(npm -v)
          - npm install

      - name: lint
        commands:
          - npm run lint

      - name: build
        commands:
          - npm run build

  - name: Artifact
    steps:
      - name: publish zip
        template: zip
        variables:
          artifact_directory: dist
          artifact_name: SPA_ZIP_ARTIFACT

  - name: Deploy
    steps:
      - name: NGINX
        commands:
          - "sshpass -p teste123@ ssh -o \"StrictHostKeyChecking=no\" -tt root@172.17.0.2 'cd /etc/nginx/www \
             && rm -rf angular_spa_test \
             && curl -O https://plataform-agent-artifacts.s3.sa-east-1.amazonaws.com/SPA_REACT.zip \
             && unzip SPA_REACT.zip -d angular_spa_test"