image: spa_build_env
repository: https://github.com/levidousseaux/react-sample.git
stages:
  - name: CI
    steps:
      - name: install
        commands:
          - echo 'node version:' $(node -v)
          - echo 'npm version:' $(npm -v)
          - npm install

      - name: lint
        commands:
          - npm run lint

      - name: build
        commands:
          - npm run build

  - name: CD
    steps:
      - name: PRODUCTION
        commands:
          - echo deploy into nginx